// <auto-generated />
using System;
using EF2First.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF2First.Migrations
{
    [DbContext(typeof(ITIEF))]
    [Migration("20240308165006_C5")]
    partial class C5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF2First.Models.Author", b =>
                {
                    b.Property<int>("Auth_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Auth_id"));

                    b.Property<DateTime>("Joindate")
                        .HasColumnType("date");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Auth_id");

                    b.ToTable("author");
                });

            modelBuilder.Entity("EF2First.Models.Catalog", b =>
                {
                    b.Property<int>("Ct_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ct_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ct_id");

                    b.ToTable("catalog");
                });

            modelBuilder.Entity("EF2First.Models.New", b =>
                {
                    b.Property<int>("New_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("New_id"));

                    b.Property<int>("Au_id")
                        .HasColumnType("int");

                    b.Property<int>("Cat_id")
                        .HasColumnType("int");

                    b.Property<string>("bref")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("date")
                        .HasColumnType("date");

                    b.Property<string>("descr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("New_id");

                    b.HasIndex("Au_id");

                    b.HasIndex("Cat_id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("EF2First.Models.New", b =>
                {
                    b.HasOne("EF2First.Models.Author", "author")
                        .WithMany("News")
                        .HasForeignKey("Au_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF2First.Models.Catalog", "cat")
                        .WithMany("News")
                        .HasForeignKey("Cat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");

                    b.Navigation("cat");
                });

            modelBuilder.Entity("EF2First.Models.Author", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("EF2First.Models.Catalog", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
